/* viz_prefix_lm_mask.js
   Concept taught: prefix-LM masking is the attention rule π₀.5 inherits from PaliGemma.
   The prefix (image patches + text) is mutually bidirectional; the suffix (generated
   tokens) reads all the prefix and only earlier suffix tokens (causal triangle).
*/
(function () {
  const C = window.PiColors;
  const canvas = document.getElementById('viz-mask');
  if (!canvas) return;
  const W = 900, H = 560;
  const ctx = setupHiDPICanvas(canvas, W, H);

  // Token roster: image patches × 16, text tokens × 5, generated suffix tokens × 3.
  // We expose prefix length as a slider, but keep the *content* stable: 0..15 image,
  // 16..20 text, 21..23 suffix. The slider re-positions the prefix/suffix split,
  // which lets the reader see how the mask shape deforms.
  const N = 24;
  const PATCH_END = 16;     // tokens 0..15 are image
  const TEXT_END  = 21;     // 16..20 are text
  // tokens 21..23 are model-generated by default

  let prefixLen = 21;       // slider value (last index belonging to prefix is prefixLen-1)
  let hoverRow = -1;

  // ─── token labels (compact)
  const tokenLabel = (i) => {
    if (i < PATCH_END) return `p${i}`;
    if (i < TEXT_END) return ['pick', 'up', 'the', 'spo', 'nge'][i - PATCH_END];
    return ['s' + (i - TEXT_END)][0]; // s0, s1, s2
  };
  const tokenKind = (i) => {
    if (i < PATCH_END) return 'image';
    if (i < TEXT_END) return 'text';
    return 'suffix';
  };

  function maskAllowed(i, j) {
    // i = query (row), j = key (col); is it allowed?
    const iSuffix = i >= prefixLen;
    const jSuffix = j >= prefixLen;
    if (!iSuffix && !jSuffix) return 'pp';   // prefix-prefix bidirectional
    if (iSuffix && !jSuffix) return 'sp';    // suffix reading prefix
    if (iSuffix && jSuffix) return j <= i ? 'ss' : null;  // causal in suffix
    return null;                              // prefix attending into suffix → blocked
  }

  function draw() {
    ctx.clearRect(0, 0, W, H);

    // ─── layout
    const gridSize = 380;
    const gridX = 130;
    const gridY = 70;
    const cell = gridSize / N;

    // axes labels
    ctx.fillStyle = C.inkMuted;
    ctx.font = '500 11px Inter';
    ctx.fillText('QUERY  ↓', gridX - 90, gridY + 14);
    ctx.fillText('KEY  →', gridX + gridSize - 24, gridY - 12);

    // legend baseline labels
    for (let i = 0; i < N; i++) {
      // y axis
      ctx.font = '9px JetBrains Mono';
      ctx.fillStyle = i < prefixLen ? (i < PATCH_END ? C.vlm : C.vlm) : C.action;
      ctx.fillText(tokenLabel(i), gridX - 36, gridY + i * cell + cell / 2 + 3);
      // x axis
      ctx.save();
      ctx.translate(gridX + i * cell + cell / 2, gridY + gridSize + 6);
      ctx.rotate(-Math.PI / 4);
      ctx.fillText(tokenLabel(i), 0, 8);
      ctx.restore();
    }

    // ─── cells
    for (let i = 0; i < N; i++) {
      for (let j = 0; j < N; j++) {
        const k = maskAllowed(i, j);
        let fill;
        if (k === 'pp') fill = 'rgba(180,140,255,0.55)';     // green/teal isn't an option per palette;
        // use VLM purple for prefix↔prefix to match palette identity
        else if (k === 'sp') fill = 'rgba(94,234,212,0.55)';  // teal — suffix reads prefix
        else if (k === 'ss') fill = 'rgba(255,168,77,0.55)';  // amber — suffix sees suffix (causal)
        else fill = '#2a2c33';                                // blocked

        ctx.fillStyle = fill;
        ctx.fillRect(gridX + j * cell + 0.5, gridY + i * cell + 0.5, cell - 1, cell - 1);
      }
    }

    // border
    ctx.strokeStyle = C.ruleStrong;
    ctx.lineWidth = 1;
    ctx.strokeRect(gridX, gridY, gridSize, gridSize);

    // prefix split line
    const splitX = gridX + prefixLen * cell;
    ctx.strokeStyle = C.data;
    ctx.lineWidth = 1.5;
    ctx.setLineDash([4, 3]);
    ctx.beginPath();
    ctx.moveTo(splitX, gridY); ctx.lineTo(splitX, gridY + gridSize);
    ctx.moveTo(gridX, splitX - gridX + gridY); ctx.lineTo(gridX + gridSize, splitX - gridX + gridY);
    ctx.stroke();
    ctx.setLineDash([]);

    // hover row
    if (hoverRow >= 0) {
      ctx.strokeStyle = C.ink;
      ctx.lineWidth = 1.5;
      ctx.strokeRect(gridX - 1, gridY + hoverRow * cell - 1, gridSize + 2, cell + 2);
    }

    // ─── token rail above
    drawRail(gridX, 26, gridSize, cell);

    // ─── side panel: explain what hovered row attends to
    const px = gridX + gridSize + 50;
    const py = gridY;
    ctx.fillStyle = C.inkMuted;
    ctx.font = '500 11px Inter';
    ctx.fillText('WHAT TOKEN ' + (hoverRow >= 0 ? hoverRow : '(hover)') + ' SEES', px, py);

    if (hoverRow >= 0) {
      const role = hoverRow < prefixLen ? 'prefix token' : 'suffix token';
      const colour = hoverRow < prefixLen ? C.vlm : C.action;
      ctx.fillStyle = colour;
      ctx.font = '600 14px Inter';
      ctx.fillText(role + '  "' + tokenLabel(hoverRow) + '"', px, py + 22);

      // count how many keys are visible
      let visible = 0;
      for (let j = 0; j < N; j++) if (maskAllowed(hoverRow, j)) visible++;
      ctx.fillStyle = C.ink;
      ctx.font = '13px Source Serif 4';
      ctx.fillText(`attends to ${visible} of ${N} tokens`, px, py + 46);

      // explanation
      ctx.font = '13px Source Serif 4';
      ctx.fillStyle = C.inkMuted;
      let explain = '';
      if (hoverRow < prefixLen) {
        explain = 'A prefix token sees every other prefix token in both directions, but cannot peek into the suffix it has not yet generated.';
      } else if (hoverRow === prefixLen) {
        explain = 'The first suffix token reads the entire prefix and only itself; nothing has been generated yet.';
      } else {
        explain = 'A suffix token reads all the prefix and only suffix tokens that came before it (the causal triangle).';
      }
      wrap(explain, px, py + 76, 280, 18);
    }

    // ─── legend strip below grid
    const ly = gridY + gridSize + 70;
    ctx.fillStyle = C.inkMuted;
    ctx.font = '500 11px Inter';
    ctx.fillText('BLOCKS', 60, ly - 6);
    legendBox(60, ly, 'rgba(180,140,255,0.55)', 'prefix ↔ prefix  (bidirectional)');
    legendBox(60 + 230, ly, 'rgba(94,234,212,0.55)', 'suffix → prefix  (read input)');
    legendBox(60 + 460, ly, 'rgba(255,168,77,0.55)', 'suffix → suffix  (causal)');
    legendBox(60 + 690, ly, '#2a2c33', 'blocked');
  }

  function drawRail(x, y, totalW, cell) {
    // a strip of token squares above the matrix, colored by kind
    for (let i = 0; i < N; i++) {
      const k = tokenKind(i);
      const isSuffix = i >= prefixLen;
      ctx.fillStyle = isSuffix ? 'rgba(255,168,77,0.55)' :
        (k === 'image' ? 'rgba(180,140,255,0.55)' : 'rgba(180,140,255,0.85)');
      ctx.fillRect(x + i * cell, y, cell - 0.5, 18);
    }
    ctx.fillStyle = C.inkDim;
    ctx.font = '9px JetBrains Mono';
    ctx.fillText('image patches', x + 1, y - 4);
    ctx.fillText('text', x + PATCH_END * cell + 1, y - 4);
    ctx.fillText('suffix', x + prefixLen * cell + 1, y - 4);
  }

  function legendBox(x, y, fill, text) {
    ctx.fillStyle = fill;
    ctx.fillRect(x, y, 16, 14);
    ctx.strokeStyle = C.rule;
    ctx.strokeRect(x + 0.5, y + 0.5, 15, 13);
    ctx.fillStyle = C.ink;
    ctx.font = '12px Inter';
    ctx.fillText(text, x + 22, y + 11);
  }

  function wrap(text, x, y, maxW, lh) {
    const words = text.split(' ');
    let line = '';
    let yy = y;
    for (const w of words) {
      const test = line ? line + ' ' + w : w;
      if (ctx.measureText(test).width > maxW && line) {
        ctx.fillText(line, x, yy);
        line = w; yy += lh;
      } else {
        line = test;
      }
    }
    if (line) ctx.fillText(line, x, yy);
  }

  // ─── interactions ────────────────────────────────────────────────────
  const slider = document.getElementById('mask-prefix');
  const sliderOut = document.getElementById('mask-prefix-out');
  slider.addEventListener('input', () => {
    prefixLen = parseInt(slider.value, 10);
    sliderOut.textContent = String(prefixLen);
    draw();
  });

  canvas.addEventListener('mousemove', (e) => {
    const r = canvas.getBoundingClientRect();
    const x = (e.clientX - r.left) * (W / r.width);
    const y = (e.clientY - r.top) * (H / r.height);
    const gridX = 130, gridY = 70, gridSize = 380;
    const cell = gridSize / N;
    if (x < gridX || x > gridX + gridSize || y < gridY || y > gridY + gridSize) {
      if (hoverRow !== -1) { hoverRow = -1; draw(); }
      return;
    }
    const row = Math.floor((y - gridY) / cell);
    if (row !== hoverRow) { hoverRow = row; draw(); }
  });
  canvas.addEventListener('mouseleave', () => { hoverRow = -1; draw(); });

  draw();
})();
